# Generated by Django 5.0.1 on 2024-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_country_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='has_criminal_issues',
            field=models.BooleanField(default=False),
        ),
    ]
